Implement offline accounts
Lea-fish/Leafish pull request #228
Opened 2022-03-04 17:50 UTC by schitcrafter

In the GUI, simply don't put in a password, and the account will become an offline account. Tested on Spigot 1.8.8, Spigot 1.12.2, and Spigot 1.16.5.

Maybe it would be nice to easily distinguish between offline and online accounts in the account selection screen, if this is desirable then either implement it (maintainers can edit this pr) or tell me.

2022-03-06 19:43 UTC, terrarier2111 requested changes

2022-03-06 19:43 UTC, terrarier2111 commented on protocol/src/protocol/offline_acc.rs
> +            uuid: Some(test),
Is it possible to use None here instead of a random value, or does that cause issues?

2022-03-06 19:43 UTC, terrarier2111 commented on protocol/src/protocol/offline_acc.rs
> +        let test = std::iter::repeat(())
Could you rename test to something meaningful?

2022-03-06 19:44 UTC, terrarier2111 commented
Also could you make "logging" into an offline account more explicit in terms of UI?

2022-03-06 21:24 UTC, terrarier2111 commented on protocol/Cargo.toml
> +rand = "0.8.4"
I think we can drop this dependency

2022-03-06 21:26 UTC, terrarier2111 commented on protocol/src/protocol/login.rs
> +    /// Will return false if the account is a offline account,
"a offline account" -> "an offline account"

2022-03-07 20:43 UTC, terrarier2111 commented
Thanks for the great work!

2022-03-07 20:44 UTC, merged

2023-09-05 08:24 UTC, andreaf74 commented
Hello tried to login without password to get an offline account, but it gives me

"protocol error: ForbiddenOperationException: Forbidden"

Should I specify something on the command line too?

I see that in Stevenarella  you can specify a username and server address using -u and -s command line options which seem to be missing in LeaFish.

Thanks